# Generated by Django 5.1 on 2024-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
